SELECT prodid, prodname FROM products;
create database movingout;
drop database movingout;
use movingout;
create table products(
prodid int primary key not null auto_increment,
prodname varchar(50) not null,
category varchar(50) not null,
descr varchar(200) not null,
price int not null,
quantity int not null,
prod_image varchar(50) not null
);
insert into products(prodname,category,descr,price,quantity,prod_image) values
('Bed','Furniture','5 by 6. Choose between cushioned and non-cushioned headrest.',13500,5,'bed.jpg'),
('L seat','Furniture','6 seater couch.Other places 50k or 55k',55000,5,'couch.jpg'),
('5 seater','Furniture','3 seater plus 2 seater 40k or 50k',45000,5,'couchicon.png'),
('TV stand','Furniture','5ft at 14k or 8.5k.6ft at 10.5k or 12k',8500,5,'tvstand.jpg'),
('Coffee table','Furniture','Nesting round table at 4.5k or 8k.',6000,5,'cotable.jpg'),
('Shoe rack','Furniture','8 tier wooden one or 3 by 4 at 7k',7000,5,'shoerack.jpg'),
('Full body mirror','Furniture','Buy with stand.41 cm at 2.7k',4000,5,'mirror.jpg'),
('Arm chair','Furniture','Most at 20k',20000,5,'armchair.png'),
('C Table','Furniture','Metallic at 4k. Curved edge at 2k - 3k ',5000,5,'ctable.jpg'),
('Egg swing chair','Furniture','Hammock egg swing chair',13500,5,'swing_chair.jpg'),
('Eames chair','Furniture','Padded and non-padded version. Can use for vanity area.',3000,5,'eameschair.jpg'),
('Nightstand','Furniture','Place beside bed.',5000,5,'nightstand.jpg'),
('Side table','Furniture','Place beside couch to hold decor.',1500,5,'sidetable.jpg'),
('Bean bag','Furniture','Medium at 6.k, large at 9.5k and extra large at 15k',15000,5,'beanbag.jpg'),
('Vanity table','Furniture','Comes with storage for makeup, skin care products and hair products.',25000,5,'vanitytable.jpg'),

('Electric kettle','Electronics','For cooking or washing clothes or dishes',2500,5,'electrickettle.jpg'),
('Electric iron','Electronics','Come in handy because I like official wear.',2000,5,'electriciron.jpg'),
('Microwave','Electronics','Look for one with oven and grill ability.',15000,5,'microwave.jpg'),
('Television','Electronics','43 inch upwards. Look for 4k resolution and good OS.',30000,5,'tv.jpg'),
('Cooker','Electronics','60 by 60. From 24k, 27k. Choose eletcric oven with fan.',30000,5,'cooker.jpg'),
('Water dispenser','Electronics','Preferrably bottom load. I do not want to lift water bottles.',6000,5,'dispenser.jpg'),
('Fridge','Electronics','138 litres price range Ksh.24k to 36k. 90 litres 23k',30000,5,'fridge.jpg'),
('Washing machine','Electronics','10kg W 6kg D @ 50k.TCL 8kg @ 42k.Hisense 7Kg @ 41k.Hisense 6Kg at 35k',45000,5,'washingm.jpg'),
('Air fryer','Electronics','Cooking french fries, sausages, meat and toast bread',6000,5,'fryer.jpg'),
('Hand mixer','Electronics','Prices from 2k to 4k',3000,5,'handmixer.jpg'),
('Floor lamp','Electronics','Alternative Chinese paper lantern at 150 or table lamp at 1000',3500,5,'floorlamp.jpg'),
('Blender','Electronics','Can make Weetabix smoothies, ginger shots or blend tomatoes',2000,5,'blender.jpg'),

('Door mat','Textiles','Most are Ksh.300',300,5,'doormat.jpg'),
('10 Plastic Hangers','Textiles','Wooden hangers @ 160. Over the door hanger @ 350',330,5,'woodenhanger.jpg'),
('Bedside mat','Textiles','Preferrably rectangle like mine. Price to 2k',800,5,'bedmat.jpg'),
('2 Bed pillows','Textiles','Can get at 400',500,5,'ppillow.jpg'),
('Duvet','Textiles','Comes with bedsheet and 2 pillow cases',1300,5,'bedding.jpg'),
('Carpet','Textiles','Size 6.5 × 9.5 or 8 × 11. Color ream,beige or grey.7 by 10 at 5.8k',9000,5,'carpet.jpg'),
('Closet organizer','Textiles','To hold T shirts and socks',350,5,'closet.jpg'),
('Decorative pillow','Textiles','Pillow cases at 500.Velvet cases 45 by 45cm @300. Sunflower @ 600',200,5,'dpillow.jpg'),

('Pasta bowls','Utensils','Set price 6 at 1000 or 1400.',1400,5,'plates.jpg'),
('Knife','Utensils','Can find one for 100.',1000,5,'knife.jpg'),
('Grater','Utensils','4 sided one',200,5,'grater.jpg'),
('6 Spoons','Utensils','Other price 6 @ 350. Gold spoons 6 @ 400.',100,5,'spoons.jpg'),
('2 Sufuria','Utensils','One for chai other for ugali',500,5,'sufuria.jpg'),
('Gas','Utensils','6kg Gas - 1620 Cylinder - 1800. 13kg Gas - 3510 Cylinder - 3400.',7000,5,'gas.jpg'),
('2 Cooking sticks','Utensils','Cooking ugali. Plus for cooking rice or stew at 100',100,5,'mwiko.jpg'),
('Tea sieve','Utensils','Metal one I guess at 100/150. Plastic at 50',100,5,'sieve.jpg'),
('Steel pots','Utensils','Set price 5 at 2900 or 3500.',3500,5,'steelpots.jpg'),
('Thermos','Utensils','Purchase 1.8 litres',500,5,'thermos.jpg'),
('Mugs','Utensils','Set of 6 at 460 or 650',100,5,'cup.jpg'),
('Chopping board','Utensils','Avoid plastic one. Biggest one at 650',550,5,'chopping.jpg'),
('Classy shakers','Utensils','Whimsy on Shein at ',150,5,'shakers.jpg'),
('Sugar dish','Utensils','Glass one at 250/300 ',300,5,'sdish.jpg'),
('Metal fruit basket','Utensils','Be aware that it might rust.',350,5,'metalfruitbasket.jpg'),
('Pan','Utensils','Do not buy non-stick pan. Malimali shop at 280. Elsewhete 1k to 1.6k',1000,5,'pan.jpg'),
('Rice bowl','Utensils','Will want to have many whimsical ceramic bowls',100,5,'bowl.jpg'),
('Soup spoon','Utensils','Other prices depending on size - 70, 100, 350',200,5,'soupspoon.jpg'),
('Pastry brush','Utensils','Pastry brush - 150. Spatula - 200. Whisk - 150',500,5,'pbrush.png'),
('Wooden egg tray','Utensils','Plastic at 350 - 1k',2000,5,'eggtray.jpg'),
('Rolling pin','Utensils','Prefer wooden classic one',200,5,'rollingpin.jpg'),

('Toilet brush','Cleaning','Aesthetic ones at 750 to 1k',100,5,'toiletbrush.jpg'),
('Pegs','Cleaning','Normal ones 144 at 160',150,5,'pegs.jpg'),
('Soap holder','Cleaning','Basic at 100. Others at 750 to 1k',500,5,'soapholder.jpg'),
('Broom','Cleaning','Weigh options. 100 at Mia duck.To 800',350,5,'broom.jpg'),
('Bucket','Cleaning','Depends on capacity.',350,5,'bucket.jpg'),
('Dustbin','Cleaning','Exact - Ksh.850. Plastic - Ksh. 200. Pedal bin - 500 to 2700',850,5,'dustbin.jpg'),
('Mop','Cleaning','Normal mop - Ksh.150. Spin mop - 1500. Spin mop has bad reviews.',150,5,'mop.jpg'),
('Fabric Laundry basket','Cleaning','Look for one that the inside lining can be washed. Other price is Ksh.3500',1500,5,'laundry_hamper.jpg'),
('Plastic laundry basket','Cleaning','Shapes are rectangular or cyndrical. Might need two. Other price is Ksh.700/750',550,5,'laundry_basket.jpg');
